### ISSUE TITLE
Simplified geometry files?

### ISSUE THREAD

**Issue by thejeshgn** [bnamita/Village_Mapping_v2#1]
Great wok. Congratulations.

The geometry files used in this application are huge. They are about ~30MB each. These are great for offline apps or while running locally.

But if this is going to be a web application then it has to be much smaller size or the application willl lag.

Few options are:
- Split it to taluk level so you download very small amount
- or use a simplified version if the visualisation going to be just a choropleth.

**Comment by thejeshgn** [comment]
Here is an how-to on simplifying https://www.youtube.com/watch?v=MTfpQ2cG9CU

**Comment by answerquest** [comment]
Done! See https://docs.google.com/document/d/1JzdHpGpuNBqad717gLa2M2hQ1rMMLLv6FWdxw6-b9Cs/pub
Used mapshaper.org 's simplify feature

**Comment by bnamita** [comment]
I've updated the project to use lighter versions of geometry files shared by @answerquest.
